apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
    app.kubernetes.io/instance: devsec
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: '0'
      labels:
        app: backend
    spec:
      containers:
        - image: >-
            ghcr.io/rupesh-hub/user-management-service:sha-2a2707b4c39c5aa9fbeba6188a4fcc11b28b6736
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8181
          resources:
            limits:
              cpu: '0.5'
              memory: 512Mi
            requests:
              cpu: '0.2'
              memory: 256Mi
      imagePullSecrets:
        - name: github-container-registry
