apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend

spec:
  type: ClusterIP
  ports:
    - port: 8181
      targetPort: 8181
      protocol: TCP
      name: http
  selector:
    app: backend