apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      containers:
        - name: backend
          image: ghcr.io/rupesh-hub/user-management-service:sha-2a2707b4c39c5aa9fbeba6188a4fcc11b28b6736
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
      imagePullSecrets:
      - name: github-container-registry
