apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      containers:
        - name: backend
          image: ghcr.io/rupesh-hub/user-management-service-backend:sha-e0a1ab852e41fc5b04db31afaea6975c2a4e3ab8
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
      imagePullSecrets:
      - name: github-container-registry
