kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap
  namespace: default
data:
  MYSQL_DATABASE: "user_db"
  MYSQL_ROOT_USERNAME: "root"
  MYSQL_DATASOURCE_URL: "jdbc:mysql://mysql:3306/user_db"