apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend  # Must match template.metadata.labels
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/rupesh-hub/user-management-service-frontend:sha-ee3f9e45ee55993bca76233460618e2c8dcd729d
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
      imagePullSecrets:
        - name: github-container-registry